### ISSUE TITLE
Unable to get resources which loaded by AppClassLoader.

### ISSUE THREAD

**Issue by ZekerZhayard** [McModLauncher/securejarhandler#27] opened 2021-12-19 06:46 UTC
Consider this test case:
```javascript
var Opcodes = Java.type("org.objectweb.asm.Opcodes");
var InsnList = Java.type("org.objectweb.asm.tree.InsnList");
var InsnNode = Java.type("org.objectweb.asm.tree.InsnNode");
var JumpInsnNode = Java.type("org.objectweb.asm.tree.JumpInsnNode");
var LabelNode = Java.type("org.objectweb.asm.tree.LabelNode");
var MethodInsnNode = Java.type("org.objectweb.asm.tree.MethodInsnNode");
var MethodNode = Java.type("org.objectweb.asm.tree.MethodNode");
var TryCatchBlockNode = Java.type("org.objectweb.asm.tree.TryCatchBlockNode");
var VarInsnNode = Java.type("org.objectweb.asm.tree.VarInsnNode");

function initializeCoreMod() {
    return {
        "MainTransformer": {
            "target": {
                "type": "CLASS",
                "name": "net/minecraft/client/main/Main"
            },
            "transformer": function (cn) {
                cn.methods.add(new MethodNode(Opcodes.ACC_PRIVATE | Opcodes.ACC_STATIC, "test", "()Lcpw/mods/niofs/union/UnionFileSystem;", null, null));
                for (var i = 0; i < cn.methods.length; i++) {
                    var method = cn.methods.get(i);
                    if (method.name == "test" && method.desc == "()Lcpw/mods/niofs/union/UnionFileSystem;") {
                        var insnList = new InsnList();
                        insnList.add(new InsnNode(Opcodes.ACONST_NULL));
                        insnList.add(new InsnNode(Opcodes.ARETURN));
                        method.instructions = insnList;
                    } else if (method.name == "main" && method.desc == "([Ljava/lang/String;)V") {
                        var l0 = new LabelNode(), l1 = new LabelNode(), l2 = new LabelNode(), l3 = new LabelNode();
                        var insnList = new InsnList();
                        insnList.add(l0);
                        insnList.add(new InsnNode(Opcodes.ACONST_NULL));
                        insnList.add(new MethodInsnNode(Opcodes.INVOKESTATIC, "net/minecraft/client/main/Main", "test", "()Lcpw/mods/niofs/union/UnionFileSystem;", false));
                        insnList.add(new VarInsnNode(Opcodes.ASTORE, 1));
                        insnList.add(l1);
                        insnList.add(new JumpInsnNode(Opcodes.GOTO, l3));
                        insnList.add(l2);
                        insnList.add(new VarInsnNode(Opcodes.ASTORE, 1));
                        insnList.add(l3);
                        method.instructions.insert(insnList);
                        method.tryCatchBlocks.add(new TryCatchBlockNode(l0, l1, l2, "java/lang/Throwable"));
                    }
                }
                return cn;
            }
        }
    };
}
```

This will get the following exception:
```
Exception in thread "main" java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 0
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 0
	at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassReader.readShort(ClassReader.java:3585)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassReader.<init>(ClassReader.java:194)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.computeHierarchyFromFile(TransformerClassWriter.java:150)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:112)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.getSupers(TransformerClassWriter.java:83)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.getCommonSuperClass(TransformerClassWriter.java:63)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1202)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.Frame.merge(Frame.java:1299)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.Frame.merge(Frame.java:1197)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
	at org.objectweb.asm.tree@9.1.0/org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:769)
	at org.objectweb.asm.tree@9.1.0/org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649)
	at org.objectweb.asm.tree@9.1.0/org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:133)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:632)
	at java.base/java.lang.Class.forName(Class.java:545)
	at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.5/net.minecraftforge.fml.loading.targets.ForgeClientUserdevLaunchHandler.lambda$launchService$0(ForgeClientUserdevLaunchHandler.java:38)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	... 7 more
```

This is because in the `TransformingClassLoader` instance `TRANSFORMER`, both [`packageLookup`](https://github.com/MinecraftForge/securejarhandler/blob/f81a31abecf63d567a9741f11a7b227dbb1a45fb/src/main/java/cpw/mods/cl/ModuleClassLoader.java#L231) and [`parentLoaders`](https://github.com/MinecraftForge/securejarhandler/blob/f81a31abecf63d567a9741f11a7b227dbb1a45fb/src/main/java/cpw/mods/cl/ModuleClassLoader.java#L235) do not contain `cpw.mods.niofs.union` (these two fields also do not contain any ASM/BSL/SJH package names)

**Comment by TheCurle** [comment] 2022-03-26 21:25
This issue has been transferred from [McModLauncher/modlauncher](https://github.com/McModLauncher/modlauncher).

**Comment by OrionDevelopment** [comment] 2022-03-29 08:58
> **Similar problem** It is not possible to use fat-jar libraries and utilities that conflict with Forge. For them to work, you need to add them to the classpath and ignoreModules, however, in this case, the library classes will not be available from the mod. Changing `fallbackClassLoader` to `ClassLoader.getSystemClassLoader()` solves this problem. Bytecode modification and transformation is not required and even harmful in my case

Just out of curiosity what libraries are you including in your fat-jar that are also included in Forge?
Cause normally this will cause a module collision, so I am wondering how your change to the `fallbackClassLoader` resolves this issue?

**Comment by gravit0** [comment] 2022-03-29 09:07
> > **Similar problem** It is not possible to use fat-jar libraries and utilities that conflict with Forge. For them to work, you need to add them to the classpath and ignoreModules, however, in this case, the library classes will not be available from the mod. Changing `fallbackClassLoader` to `ClassLoader.getSystemClassLoader()` solves this problem. Bytecode modification and transformation is not required and even harmful in my case
> 
> Just out of curiosity what libraries are you including in your fat-jar that are also included in Forge? Cause normally this will cause a module collision, so I am wondering how your change to the `fallbackClassLoader` resolves this issue?

Yes, without adding fat-jar to ignoreModules module conflicts occur. The library contains ASM and other libraries depending on the configuration. The library remaps its ASM into an internal package to avoid conflicts with most software, however this does not work. Libraries using JNA cannot be remapped

**Comment by OrionDevelopment** [comment] 2022-03-29 09:18
Okey interesting, since you are adding your mod to ignoreModules I wonder how it then is loaded, since it is not part of the module system.

**Comment by OrionDevelopment** [comment] 2022-03-29 09:19
But I guess it is loaded through the loader chain then...
I would need to check something like this.

**Comment by gravit0** [comment] 2022-03-29 09:25
A library is added to ignoreModules, the mod itself is loaded in the usual way. The mod refers to the library as a dependency, without reflection
If you do not change anything and add the library to the classpath, Forge will not start due to module conflicts.
If you add the library to ignoreModules then Forge loads fine but cannot access the library.
If you change `fallbackClassLoader` to `SystemClassLoader` then everything will work

**Comment by OrionDevelopment** [comment] 2022-03-29 09:30
Yeah the fact that it can not access the library is by design.....
That is kind of the issue.
We restart the classloading system in module mode on purpose with a clean slate.

Hence why I am really careful about switching this out, since that would break that compatibility.

**Comment by gravit0** [comment] 2022-03-29 09:36
If the absence of a class from the ModuleClassLoader and its availability from the SystemClassLoader is expected behavior - it might be worth adding a configurable filter that can be loaded from the SystemClassLoader

**Closed** 2022-05-23 11:53 UTC
Labels: bug
