### ISSUE TITLE
NullPointerException in classloader

### ISSUE THREAD

**Issue by noskill** [McModLauncher/securejarhandler#24] opened 2022-02-08 10:15 UTC
Hi. I am trying to load jaxb library https://github.com/eclipse-ee4j/jaxb-ri

```
Exception in thread "Thread-9" java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base/java.lang.module.Configuration.findModule(Configuration.java:548)
        at cpw.mods.securejarhandler@1.0.1/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:220)
        at cpw.mods.securejarhandler@1.0.1/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:632)
        at java.base/java.lang.Package.getPackageInfo(Package.java:432)
        at java.base/java.lang.Package.getAnnotation(Package.java:458)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.annotation.RuntimeInlineAnnotationReader.getPackageAnnotation(RuntimeInlineAnnotationReader.java:101)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.annotation.RuntimeInlineAnnotationReader.getPackageAnnotation(RuntimeInlineAnnotationReader.java:29)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.TypeInfoImpl.parseElementName(TypeInfoImpl.java:96)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.ClassInfoImpl.<init>(ClassInfoImpl.java:98)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.RuntimeClassInfoImpl.<init>(RuntimeClassInfoImpl.java:70)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.createClassInfo(RuntimeModelBuilder.java:76)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.createClassInfo(RuntimeModelBuilder.java:46)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.getClassInfo(ModelBuilder.java:214)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:66)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:46)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.getClassInfo(ModelBuilder.java:184)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:61)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:46)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.getTypeInfo(ModelBuilder.java:332)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.getTypeInfo(ModelBuilder.java:347)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:413)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:251)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:77)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1111)
        at MC-BOOTSTRAP/org.glassfish.jaxb.runtime@3.0.2/org.glassfish.jaxb.runtime.v2.ContextFactory.createContext(ContextFactory.java:140)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/jakarta.xml.bind@3.0.1/jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:274)
        at MC-BOOTSTRAP/jakarta.xml.bind@3.0.1/jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:263)
        at MC-BOOTSTRAP/jakarta.xml.bind@3.0.1/jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:243)
        at MC-BOOTSTRAP/jakarta.xml.bind@3.0.1/jakarta.xml.bind.ContextFinder.find(ContextFinder.java:407)
        at MC-BOOTSTRAP/jakarta.xml.bind@3.0.1/jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
        at MC-BOOTSTRAP/jakarta.xml.bind@3.0.1/jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
        ....
```

**Comment by OrionDevelopment** [comment] 2022-02-08 10:53
This looks like you are executing something not on the main thread.
Could this be the case, since Thread-9 is the current name.

If so you will need to manage the Context Class Loader.

**Comment by noskill** [comment] 2022-02-08 13:20
Setting class loader with Thread.currentThread().setContextClassLoader doesn't help. 

ClassLoader is loaded from the unnamed module in getPackageInfo()(Package.java from jdk).

>     private Class<?> getPackageInfo() {
>         if (packageInfo == null) {
>             // find package-info.class defined by loader
>             String cn = packageName() + ".package-info";
>             Module module = module();
>             PrivilegedAction<ClassLoader> pa = module::getClassLoader;
>             @SuppressWarnings("removal")
>             ClassLoader loader = AccessController.doPrivileged(pa);
>             Class<?> c;
>             if (loader != null) {
>                 c = loader.loadClass(module, cn);    // <-------- NullPointerException

**Comment by OrionDevelopment** [comment] 2022-02-08 13:21
Can you show me your code?
Like how are you invoking the JAXB parser?

**Comment by noskill** [comment] 2022-02-08 13:35
yes it's here  https://github.com/noskill/Vereya/blob/0093ab3609eb7b3ae3f1709cd8f141d8688ad85c/src/main/java/io/singularitynet/utils/SchemaHelper.java#L76

it's just 
> JAXBContext jaxbContext = JAXBContext.newInstance(objclass);

where objclass is a class compiled from xsd schema. I tested the code in separate project without minecraft.

**Comment by OrionDevelopment** [comment] 2022-02-08 13:46
Can you actually send me the entire stack trace and invoking code?
There is no real information in just showing me your JAXB code since that only does class loading resolving.

I need to know from where in your mod code you are invoking this and with what.

**Comment by noskill** [comment] 2022-02-08 13:57
Yes, here is entire stack trace:
```
Exception in thread "Thread-10" java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base/java.lang.module.Configuration.findModule(Configuration.java:548)
        at cpw.mods.securejarhandler@1.0.1/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:220)
        at cpw.mods.securejarhandler@1.0.1/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:632)
        at java.base/java.lang.Package.getPackageInfo(Package.java:432)
        at java.base/java.lang.Package.getAnnotation(Package.java:458)
        at org.glassfish.jaxb.runtime.v2.model.annotation.RuntimeInlineAnnotationReader.getPackageAnnotation(RuntimeInlineAnnotationReader.java:101)
        at org.glassfish.jaxb.runtime.v2.model.annotation.RuntimeInlineAnnotationReader.getPackageAnnotation(RuntimeInlineAnnotationReader.java:29)
        at org.glassfish.jaxb.runtime.v2.model.impl.TypeInfoImpl.parseTypeName(TypeInfoImpl.java:140)
        at org.glassfish.jaxb.runtime.v2.model.impl.ClassInfoImpl.<init>(ClassInfoImpl.java:102)
        at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeClassInfoImpl.<init>(RuntimeClassInfoImpl.java:70)
        at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.createClassInfo(RuntimeModelBuilder.java:76)
        at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.createClassInfo(RuntimeModelBuilder.java:46)
        at org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.getClassInfo(ModelBuilder.java:214)
        at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:66)
        at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:46)
        at org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.getClassInfo(ModelBuilder.java:184)
        at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:61)
        at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:46)
        at org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.getTypeInfo(ModelBuilder.java:332)
        at org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.getTypeInfo(ModelBuilder.java:347)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:413)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:251)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:77)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1111)
        at org.glassfish.jaxb.runtime.v2.ContextFactory.createContext(ContextFactory.java:140)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/jakarta.xml.bind@3.0.1/jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:274)
        at MC-BOOTSTRAP/jakarta.xml.bind@3.0.1/jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:263)
        at MC-BOOTSTRAP/jakarta.xml.bind@3.0.1/jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:243)
        at MC-BOOTSTRAP/jakarta.xml.bind@3.0.1/jakarta.xml.bind.ContextFinder.find(ContextFinder.java:407)
        at MC-BOOTSTRAP/jakarta.xml.bind@3.0.1/jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
        at MC-BOOTSTRAP/jakarta.xml.bind@3.0.1/jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
        at TRANSFORMER/vereya@0.1.0/io.singularitynet.utils.SchemaHelper.getJAXBContext(SchemaHelper.java:76)
        at TRANSFORMER/vereya@0.1.0/io.singularitynet.utils.SchemaHelper.deserialiseObject(SchemaHelper.java:101)
        at TRANSFORMER/vereya@0.1.0/io.singularitynet.ClientStateMachine.decodeMissionInit(ClientStateMachine.java:309)
        at TRANSFORMER/vereya@0.1.0/io.singularitynet.ClientStateMachine$2.onCommand(ClientStateMachine.java:517)
        at TRANSFORMER/vereya@0.1.0/io.singularitynet.utils.TCPInputPoller.commandReceived(TCPInputPoller.java:280)
        at TRANSFORMER/vereya@0.1.0/io.singularitynet.utils.TCPInputPoller$TCPConnectionHandler.run(TCPInputPoller.java:385)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by noskill** [comment] 2022-02-08 14:04
I can make docker image if that helps

**Comment by OrionDevelopment** [comment] 2022-02-08 14:05
How are you setting your class loader?

**Comment by OrionDevelopment** [comment] 2022-02-08 14:06
Also I am not sure this will work without shading..... Since it will likely load JAXB as a none game library on newer versions.

**Comment by noskill** [comment] 2022-02-08 14:12
So should i just move xml parsing to whatever thread is used by minecraftforge to trigger events?

**Comment by noskill** [comment] 2022-02-08 14:14
> How are you setting your class loader?

I tried adding these lines of code before jaxb context creation.
```
ClassLoader c = new ClassLoader() {};
Thread.currentThread().setContextClassLoader(c);
```

**Comment by OrionDevelopment** [comment] 2022-02-08 14:19
> ClassLoader c = new ClassLoader() {};
> Thread.currentThread().setContextClassLoader(c);

That does nothing....
You need to get the class loader of the modclass.

Which you can do via: `Modclass.class.getClassLoader()`

**Comment by noskill** [comment] 2022-02-08 14:49
I tried this:
```
        ClassLoader c = Vereya.class.getClassLoader();
        ClassLoader b = Thread.currentThread().getContextClassLoader();
        System.out.println(c.equals(b));
        Thread.currentThread().setContextClassLoader(c);
        JAXBContext jaxbContext = getJAXBContext(objclass);
```

It gives the same stacktrace, and prints true because c and b are the same. It's instance of TransformingClassLoader

**Comment by OrionDevelopment** [comment] 2022-02-08 15:18
Which minecraft version are you using?

**Comment by OrionDevelopment** [comment] 2022-02-08 15:24
Then your approach will not work.
Forge uses a custom module system and you can not replace or modify -cp since it does not use that anymore.

If you need additional libraries you will need to shade them into your mod jar to get them to load into the correct accessible library.

**Comment by OrionDevelopment** [comment] 2022-02-08 15:28
Basically follow this guide to get them to load: <https://gist.github.com/SizableShrimp/66b22f1b24c255e1491c8d98d3f11f83>

Closing issue since this is caused by improper loading of additional dependencies and as such outside of the scope Forge/SJH/Modlauncher

**Closed by OrionDevelopment** 2022-02-08 15:28 UTC

**Comment by noskill** [comment] 2022-02-08 15:40
Thanks man, i really appreciate it. It was very confusing bug for me.

**Comment by noskill** [comment] 2022-02-09 13:02
@OrionDevelopment i got exactly the same stacktrace with fat jar. Could you please reopen the issue?

**Comment by noskill** [comment] 2022-02-09 16:08
@OrionDevelopment 

I double checked it, but with fat jar the bug is still here:

```
[20:05:14] [Thread-9/ERROR]: exception parsing xml
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
        at java.lang.module.Configuration.findModule(Configuration.java:548) ~[?:?]
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:220) ~[securejarhandler-1.0.1.jar:?]
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-1.0.1.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:632) ~[?:?]
        at java.lang.Package.getPackageInfo(Package.java:432) ~[?:?]
        at java.lang.Package.getAnnotation(Package.java:458) ~[?:?]
        at org.glassfish.jaxb.runtime.v2.model.annotation.RuntimeInlineAnnotationReader.getPackageAnnotation(RuntimeInlineAnnotationReader.java:101) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at org.glassfish.jaxb.runtime.v2.model.annotation.RuntimeInlineAnnotationReader.getPackageAnnotation(RuntimeInlineAnnotationReader.java:29) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at org.glassfish.jaxb.runtime.v2.model.impl.TypeInfoImpl.parseElementName(TypeInfoImpl.java:96) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at org.glassfish.jaxb.runtime.v2.model.impl.ClassInfoImpl.<init>(ClassInfoImpl.java:98) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeClassInfoImpl.<init>(RuntimeClassInfoImpl.java:70) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.createClassInfo(RuntimeModelBuilder.java:76) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.createClassInfo(RuntimeModelBuilder.java:46) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.getClassInfo(ModelBuilder.java:214) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:66) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:46) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.getClassInfo(ModelBuilder.java:184) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:61) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:46) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.getTypeInfo(ModelBuilder.java:332) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.getTypeInfo(ModelBuilder.java:347) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:413) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:251) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:77) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1111) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at org.glassfish.jaxb.runtime.v2.ContextFactory.createContext(ContextFactory.java:140) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:274) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:263) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:395) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:691) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:632) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at io.singularitynet.utils.SchemaHelper.getJAXBContext(SchemaHelper.java:76) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at io.singularitynet.utils.SchemaHelper.deserialiseObject(SchemaHelper.java:101) ~[vereya-0.1.0.jar%2352!/:0.1.0]
        at io.singularitynet.ClientStateMachine.decodeMissionInit(ClientStateMachine.java:307) [vereya-0.1.0.jar%2352!/:0.1.0]
        at io.singularitynet.ClientStateMachine$1.onCommand(ClientStateMachine.java:519) [vereya-0.1.0.jar%2352!/:0.1.0]
        at io.singularitynet.utils.TCPInputPoller.commandReceived(TCPInputPoller.java:280) [vereya-0.1.0.jar%2352!/:0.1.0]
        at io.singularitynet.utils.TCPInputPoller$TCPConnectionHandler.run(TCPInputPoller.java:385) [vereya-0.1.0.jar%2352!/:0.1.0]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by vsbogd** [comment] 2022-02-09 16:59
Looks like the issue happens because the unnamed module case is not handled properly in `ModuleClassLoader`:
https://github.com/McModLauncher/securejarhandler/blob/41ecce081706f0596abeab8c060fecfb5deb4693/src/main/java/cpw/mods/cl/ModuleClassLoader.java#L222-L228

In JDK code the case when `moduleName` is `null` is handled separately (see [JDK code mirror](https://github.com/openjdk/jdk17/blob/4afbcaf55383ec2f5da53282a1547bac3d099e9d/src/java.base/share/classes/java/lang/ClassLoader.java#L746-L753)):
```java
    protected Class<?> findClass(String moduleName, String name) {
        if (moduleName == null) {
            try {
                return findClass(name);
            } catch (ClassNotFoundException ignore) { }
        }
        return null;
    }
```

**Comment by OrionDevelopment** [comment] 2022-02-09 17:04
This is completely by design.
SJH expects everything mod related to be in a module, no buts or ifs (Okey maybe there are some, but for mod code there is no exception).
If you are somehow loading from the unnamed module, that means your shading went wrong.

I suggest visiting the MinecraftForge discord, and requesting help there.

**Comment by cpw** [comment] 2022-02-09 17:24
Locking, because clearly the submitter has no idea how classloading works.

**Comment by OrionDevelopment** [comment] 2022-02-10 14:08
Marked as duplicate of #13
